// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} html
 * @param {Big} order
 * @returns {Promise.<void>}
 */
export async function DS_wyy_player(html, order) {
	// BEGIN USER CODE
	var x=document.getElementsByClassName("mx-name-index-"+(order-1))[0];

	x.innerHTML=(html);

	// END USER CODE
}
