// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databaseconnector.proxies;

public class ParameterList extends databaseconnector.proxies.Parameter
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseConnector.ParameterList";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SQLTypeName("SQLTypeName"),
		ParameterMode("ParameterMode"),
		Position("Position"),
		Name("Name"),
		ParameterList_Parameter("DatabaseConnector.ParameterList_Parameter");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ParameterList(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ParameterList(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parameterListMendixObject)
	{
		super(context, parameterListMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, parameterListMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * @deprecated Use 'ParameterList.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databaseconnector.proxies.ParameterList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databaseconnector.proxies.ParameterList.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static databaseconnector.proxies.ParameterList initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new databaseconnector.proxies.ParameterList(context, mendixObject);
	}

	public static databaseconnector.proxies.ParameterList load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databaseconnector.proxies.ParameterList.initialize(context, mendixObject);
	}

	/**
	 * @return value of SQLTypeName
	 */
	public final java.lang.String getSQLTypeName()
	{
		return getSQLTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of SQLTypeName
	 */
	public final java.lang.String getSQLTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SQLTypeName.toString());
	}

	/**
	 * Set value of SQLTypeName
	 * @param sqltypename
	 */
	public final void setSQLTypeName(java.lang.String sqltypename)
	{
		setSQLTypeName(getContext(), sqltypename);
	}

	/**
	 * Set value of SQLTypeName
	 * @param context
	 * @param sqltypename
	 */
	public final void setSQLTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sqltypename)
	{
		getMendixObject().setValue(context, MemberNames.SQLTypeName.toString(), sqltypename);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ParameterList_Parameter
	 */
	public final java.util.List<databaseconnector.proxies.Parameter> getParameterList_Parameter() throws com.mendix.core.CoreException
	{
		return getParameterList_Parameter(getContext());
	}

	/**
	 * @param context
	 * @return value of ParameterList_Parameter
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<databaseconnector.proxies.Parameter> getParameterList_Parameter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<databaseconnector.proxies.Parameter> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.ParameterList_Parameter.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(databaseconnector.proxies.Parameter.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of ParameterList_Parameter
	 * @param parameterlist_parameter
	 */
	public final void setParameterList_Parameter(java.util.List<databaseconnector.proxies.Parameter> parameterlist_parameter)
	{
		setParameterList_Parameter(getContext(), parameterlist_parameter);
	}

	/**
	 * Set value of ParameterList_Parameter
	 * @param context
	 * @param parameterlist_parameter
	 */
	public final void setParameterList_Parameter(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<databaseconnector.proxies.Parameter> parameterlist_parameter)
	{
		var identifiers = parameterlist_parameter
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.ParameterList_Parameter.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databaseconnector.proxies.ParameterList that = (databaseconnector.proxies.ParameterList) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Override
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
