// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package databaseconnector.proxies;

public class Parameter
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject parameterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DatabaseConnector.Parameter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ParameterMode("ParameterMode"),
		Position("Position"),
		Name("Name");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Parameter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Parameter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject parameterMendixObject)
	{
		if (parameterMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, parameterMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.parameterMendixObject = parameterMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Parameter.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static databaseconnector.proxies.Parameter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return databaseconnector.proxies.Parameter.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static databaseconnector.proxies.Parameter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("DatabaseConnector.ParameterDatetime", mendixObject.getType())) {
			return databaseconnector.proxies.ParameterDatetime.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("DatabaseConnector.ParameterDecimal", mendixObject.getType())) {
			return databaseconnector.proxies.ParameterDecimal.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("DatabaseConnector.ParameterList", mendixObject.getType())) {
			return databaseconnector.proxies.ParameterList.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("DatabaseConnector.ParameterLong", mendixObject.getType())) {
			return databaseconnector.proxies.ParameterLong.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("DatabaseConnector.ParameterObject", mendixObject.getType())) {
			return databaseconnector.proxies.ParameterObject.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("DatabaseConnector.ParameterRefCursor", mendixObject.getType())) {
			return databaseconnector.proxies.ParameterRefCursor.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("DatabaseConnector.ParameterString", mendixObject.getType())) {
			return databaseconnector.proxies.ParameterString.initialize(context, mendixObject);
		}
		return new databaseconnector.proxies.Parameter(context, mendixObject);
	}

	public static databaseconnector.proxies.Parameter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return databaseconnector.proxies.Parameter.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 * @throws com.mendix.core.CoreException
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * Set value of ParameterMode
	 * @param parametermode
	 */
	public final databaseconnector.proxies.ParameterMode getParameterMode()
	{
		return getParameterMode(getContext());
	}

	/**
	 * @param context
	 * @return value of ParameterMode
	 */
	public final databaseconnector.proxies.ParameterMode getParameterMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ParameterMode.toString());
		if (obj == null) {
			return null;
		}
		return databaseconnector.proxies.ParameterMode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ParameterMode
	 * @param parametermode
	 */
	public final void setParameterMode(databaseconnector.proxies.ParameterMode parametermode)
	{
		setParameterMode(getContext(), parametermode);
	}

	/**
	 * Set value of ParameterMode
	 * @param context
	 * @param parametermode
	 */
	public final void setParameterMode(com.mendix.systemwideinterfaces.core.IContext context, databaseconnector.proxies.ParameterMode parametermode)
	{
		if (parametermode != null) {
			getMendixObject().setValue(context, MemberNames.ParameterMode.toString(), parametermode.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ParameterMode.toString(), null);
		}
	}

	/**
	 * @return value of Position
	 */
	public final java.lang.Integer getPosition()
	{
		return getPosition(getContext());
	}

	/**
	 * @param context
	 * @return value of Position
	 */
	public final java.lang.Integer getPosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Position.toString());
	}

	/**
	 * Set value of Position
	 * @param position
	 */
	public final void setPosition(java.lang.Integer position)
	{
		setPosition(getContext(), position);
	}

	/**
	 * Set value of Position
	 * @param context
	 * @param position
	 */
	public final void setPosition(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer position)
	{
		getMendixObject().setValue(context, MemberNames.Position.toString(), position);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return parameterMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final databaseconnector.proxies.Parameter that = (databaseconnector.proxies.Parameter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return entityName;
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
