// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package model.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the Model module
	public static void aCT_createTestDate(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("Model.ACT_createTestDate").withParams(params).execute(context);
	}
	public static java.lang.String dS_MusicList(IContext context, model.proxies.Music _music)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Music", _music == null ? null : _music.getMendixObject());
		return (java.lang.String) Core.microflowCall("Model.DS_MusicList").withParams(params).execute(context);
	}
}
